/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category Collect
 * @category generated
 */
export const CollectStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number
}>([['instructionDiscriminator', beet.u8]], 'CollectInstructionArgs')
/**
 * Accounts required by the _Collect_ instruction
 *
 * @property [_writable_] wrapperState
 * @property [_writable_, **signer**] collector
 * @category Instructions
 * @category Collect
 * @category generated
 */
export type CollectInstructionAccounts = {
  wrapperState: web3.PublicKey
  systemProgram?: web3.PublicKey
  collector: web3.PublicKey
}

export const collectInstructionDiscriminator = 7

/**
 * Creates a _Collect_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category Collect
 * @category generated
 */
export function createCollectInstruction(
  accounts: CollectInstructionAccounts,
  programId = new web3.PublicKey('wMNFSTkir3HgyZTsB7uqu3i7FA73grFCptPXgrZjksL')
) {
  const [data] = CollectStruct.serialize({
    instructionDiscriminator: collectInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.wrapperState,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.collector,
      isWritable: true,
      isSigner: true,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
