/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CommitMarket
 * @category generated
 */
export const CommitMarketStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number
}>([['instructionDiscriminator', beet.u8]], 'CommitMarketInstructionArgs')
/**
 * Accounts required by the _CommitMarket_ instruction
 *
 * @property [_writable_, **signer**] payer
 * @property [_writable_] market
 * @property [] magicProgram
 * @property [] magicContext
 * @category Instructions
 * @category CommitMarket
 * @category generated
 */
export type CommitMarketInstructionAccounts = {
  payer: web3.PublicKey
  market: web3.PublicKey
  magicProgram: web3.PublicKey
  magicContext: web3.PublicKey
}

export const commitMarketInstructionDiscriminator = 15

/**
 * Creates a _CommitMarket_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category CommitMarket
 * @category generated
 */
export function createCommitMarketInstruction(
  accounts: CommitMarketInstructionAccounts,
  programId = new web3.PublicKey('MNFSTqtC93rEfYHB6hF82sKdZpUDFWkViLByLd1k1Ms')
) {
  const [data] = CommitMarketStruct.serialize({
    instructionDiscriminator: commitMarketInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.market,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.magicProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.magicContext,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
