/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CrankFunding
 * @category generated
 */
export const CrankFundingStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number
}>([['instructionDiscriminator', beet.u8]], 'CrankFundingInstructionArgs')
/**
 * Accounts required by the _CrankFunding_ instruction
 *
 * @property [_writable_, **signer**] payer
 * @property [_writable_] market
 * @property [] pythPriceFeed
 * @category Instructions
 * @category CrankFunding
 * @category generated
 */
export type CrankFundingInstructionAccounts = {
  payer: web3.PublicKey
  market: web3.PublicKey
  pythPriceFeed: web3.PublicKey
}

export const crankFundingInstructionDiscriminator = 17

/**
 * Creates a _CrankFunding_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category CrankFunding
 * @category generated
 */
export function createCrankFundingInstruction(
  accounts: CrankFundingInstructionAccounts,
  programId = new web3.PublicKey('MNFSTqtC93rEfYHB6hF82sKdZpUDFWkViLByLd1k1Ms')
) {
  const [data] = CrankFundingStruct.serialize({
    instructionDiscriminator: crankFundingInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.market,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.pythPriceFeed,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
