/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category DelegateMarket
 * @category generated
 */
export const DelegateMarketStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number
}>([['instructionDiscriminator', beet.u8]], 'DelegateMarketInstructionArgs')
/**
 * Accounts required by the _DelegateMarket_ instruction
 *
 * @property [_writable_, **signer**] payer
 * @property [_writable_] market
 * @property [] ownerProgram
 * @property [] delegationProgram
 * @property [_writable_] delegationRecord
 * @property [_writable_] delegationMetadata
 * @property [_writable_] buffer
 * @category Instructions
 * @category DelegateMarket
 * @category generated
 */
export type DelegateMarketInstructionAccounts = {
  payer: web3.PublicKey
  market: web3.PublicKey
  ownerProgram: web3.PublicKey
  delegationProgram: web3.PublicKey
  delegationRecord: web3.PublicKey
  delegationMetadata: web3.PublicKey
  systemProgram?: web3.PublicKey
  buffer: web3.PublicKey
}

export const delegateMarketInstructionDiscriminator = 14

/**
 * Creates a _DelegateMarket_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category DelegateMarket
 * @category generated
 */
export function createDelegateMarketInstruction(
  accounts: DelegateMarketInstructionAccounts,
  programId = new web3.PublicKey('MNFSTqtC93rEfYHB6hF82sKdZpUDFWkViLByLd1k1Ms')
) {
  const [data] = DelegateMarketStruct.serialize({
    instructionDiscriminator: delegateMarketInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.market,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.ownerProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.delegationProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.delegationRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.delegationMetadata,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.buffer,
      isWritable: true,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
