/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { LiquidateParams, liquidateParamsBeet } from '../types/LiquidateParams'

/**
 * @category Instructions
 * @category Liquidate
 * @category generated
 */
export type LiquidateInstructionArgs = {
  params: LiquidateParams
}
/**
 * @category Instructions
 * @category Liquidate
 * @category generated
 */
export const LiquidateStruct = new beet.BeetArgsStruct<
  LiquidateInstructionArgs & {
    instructionDiscriminator: number
  }
>(
  [
    ['instructionDiscriminator', beet.u8],
    ['params', liquidateParamsBeet],
  ],
  'LiquidateInstructionArgs'
)
/**
 * Accounts required by the _Liquidate_ instruction
 *
 * @property [_writable_, **signer**] liquidator
 * @property [_writable_] market
 * @category Instructions
 * @category Liquidate
 * @category generated
 */
export type LiquidateInstructionAccounts = {
  liquidator: web3.PublicKey
  market: web3.PublicKey
  systemProgram?: web3.PublicKey
}

export const liquidateInstructionDiscriminator = 16

/**
 * Creates a _Liquidate_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category Liquidate
 * @category generated
 */
export function createLiquidateInstruction(
  accounts: LiquidateInstructionAccounts,
  args: LiquidateInstructionArgs,
  programId = new web3.PublicKey('MNFSTqtC93rEfYHB6hF82sKdZpUDFWkViLByLd1k1Ms')
) {
  const [data] = LiquidateStruct.serialize({
    instructionDiscriminator: liquidateInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.liquidator,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.market,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
